service: mlbot

provider:
  name: aws
  runtime: python3.7
  memorySize: 512 # memory >=512 MB has much more predictable performance
  timeout: 10
  region: eu-west-1
  environment:
    EndpointName: ${self:custom.sagemakerEndpointName}
    ClassifierName: ${self:custom.classifierName}
    DetectorName: ${self:custom.detectorName}
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "sagemaker:InvokeEndpoint"
       Resource: "arn:aws:sagemaker:#{AWS::Region}:#{AWS::AccountId}:endpoint/${self:custom.sagemakerEndpointName}"
    -  Effect: "Allow"
       Action:
         - "rekognition:DetectLabels"
       Resource: "*"
    -  Effect: "Allow"
       Action:
         - "lambda:InvokeFunction"
       Resource:
         - "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:custom.classifierName}"
         - "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:custom.detectorName}"

plugins:
  - serverless-pseudo-parameters

custom:
  sagemakerEndpointName: mlbot-classify-ep--2019-02-14-09-16-45
  classifierName: mlbot-${opt:stage}-classify
  detectorName: mlbot-${opt:stage}-detect

functions:
  classify:
    handler: classify.lambda_handler
  detect:
    handler: detect.lambda_handler
  handler:
    handler: handler.lambda_handler
